//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CRISP2.rc
//
#define IDS_ERRWRITEFILE                0x0001
#define IDS_ERRREADFILE                 0x0002
#define IDS_ERRCREATEFILE               0x0003
#define IDC_AX_UPDATE                   3
#define IDS_ERROPENFILE                 0x0004
#define IDC_AX_CREATE                   4
#define IDC_SAVE                        4
#define IDS_ERRNUMBEROFCHILDS           0x0006
#define IDS_ERRMEMFOROBJECT             0x0007
#define IDS_ERRINVALIDINIFILE           0x0009
#define IDS_ERR386MODE                  0x000A
#define IDS_ERR387                      0x000B
#define IDS_ERRCRVHEADER                0x000D
#define IDS_ERRCRVSTEPS                 0x000E
#define IDS_ERRCRVDATA                  0x000F
#define IDS_ERRREFINELATTICE            0x0010
#define IDS_ERRINVALIDPCX               0x0011
#define IDS_ERRSAVEASDIF                0x0012
#define IDS_ERRSAVEASIMG                0x0013
#define IDS_ERRININOTFOUND              0x0014
#define IDS_ERRINVALIDHINDX             0x0015
#define IDS_ERRINVALIDKINDX             0x0016
#define IDS_ERRNOSUCHREFL               0x0017
#define IDS_ERRINVALIDAMP               0x0018
#define IDS_ERRINVALIDPHA               0x0019
#define IDS_ERRNOPLACEFORREFL           0x001A
#define IDS_ERRFORBIDDENREFL            0x001B
#define IDS_ERRREFLALREADYEXIST         0x001C
#define IDS_ERRINVALIDIMG               0x001D
#define IDS_ERRUNSUPPORTEDFORMAT        0X001E
#define IDS_ERRUNKNOWNFORMAT            0X001F
#define IDS_ERRELMICRONOTFOUND          0X0020
#define IDS_ERRINVALIDTIF               0X0021
#define IDS_ERRDEMO                     0X0022
#define IDS_ERRINVALIDJPG               0X0023
#define IDS_ERRINVALIDMRC               0X0024
#define IDS_ERRINVALIDBMP               37
#define IDS_ERRINVALIDVIF               38
#define IDS_ERRINVALIDSPE               39
#define IDS_ERRINVALIDIP                40
#define IDS_ERRINVALIDRAW               41
#define IDS_ERRINVALIDDM2               42
#define IDS_ERRINVALIDDM3               43
#define IDS_ERRORDSPACETBL              44
#define IDS_ERRINVALIDIPF               45
#define IDS_ERRINVALIDNDR               46
#define IDS_ERRINVALIDSER               47
#define IDS_PE_NODC                     100
#define IDR_TOOLBAR1                    101
#define IDS_PE_BITBLT                   101
#define IDS_PE_STARTDOC                 102
#define IDS_PE_SETAPROC                 103
#define IDS_PE_NEWFRAME                 104
#define IDS_PE_ENDDOC                   105
#define IDS_PE_MEM                      106
#define IDS_PE_TEXTOUT                  107
#define IDC_FT_LIN                      107
#define IDC_FT_PAR                      108
#define IDC_FT_DC                       109
#define IDC_FT_SC                       110
#define IDC_FT_DEF                      111
#define IDC_FT_SAVEDEF                  112
#define IDC_LC_LINEAR                   112
#define IDC_LC_PLOT                     113
#define IDC_HKE_INVFIX                  114
#define IDC_LC_STEPS                    115
#define IDC_LC_NEG                      116
#define IDC_HKE_DELFIX                  117
#define IDC_LC_CREATE                   118
#define IDC_HKE_HELP                    119
#define IDC_LC_SX                       120
#define IDC_LC_SY                       122
#define IDC_FI_APPLY                    124
#define IDC_LC_CHANGE                   125
#define IDC_FI_L_LIST                   127
#define IDC_FI_SAVE                     128
#define IDC_FI_LOAD                     129
#define IDC_INF_EMLIST                  131
#define IDC_ELD_CENTERED                132
#define IDC_ELD_DRAWINDEX               133
#define IDC_FI_C_DEF0TXT                133
#define IDC_ELD_SMARTLR                 134
#define IDC_FI_C_DEF1TXT                134
#define IDC_DM_CELLEDGE                 135
#define IDC_ELD_DRAWAXES                135
#define IDC_ORT_G                       136
#define IDC_DM_CONTMAP                  136
#define IDC_ORT_R                       137
#define IDC_ORT_THR                     138
#define IDC_ORT_WEIGHT                  139
#define IDR_TOOLBAR2                    140
#define IDR_TOOLBAR1_OLD                141
#define IDC_ORT_EST                     142
#define IDC_OR_SH                       143
#define IDC_OR_SHK                      143
#define IDC_ORT_TP                      144
#define IDC_ORT_TV                      145
#define IDC_OR_SK                       146
#define IDC_ORT_SHE                     147
#define IDC_OR_LIST                     150
#define IDC_ORT_SH                      153
#define IDC_ORT_SK                      154
#define IDC_ORT_MAXAMP                  155
#define IDC_OR_MORE                     156
#define IDC_LC_SAVE                     157
#define IDC_OR_W1                       158
#define IDC_OR_W2                       159
#define IDC_ORT_SYNAME0                 160
#define IDD_DIALOG1                     160
#define IDC_OR_BP1                      161
#define IDC_OR_W1TITLE                  162
#define IDD_IMPORT_RAW                  162
#define IDC_OR_BRMAP                    163
#define IDR_MAINFRAME                   163
#define IDC_OR_REFINE                   164
#define IDC_ETB_LIST                    165
#define IDC_ORT_METHOD                  166
#define IDC_OR_AS                       167
#define IDC_OR_ABGS                     167
#define IDC_OR_BS                       168
#define IDC_OR_TRYALL                   169
#define IDC_OR_CREATEIMG                170
#define IDC_OR_GS                       171
#define IDC_ORT_SYNAME1                 172
#define IDC_DM_A                        173
#define IDC_ORT_AMPVSUM                 174
#define IDC_LC_LOAD                     175
#define IDC_ORT_EMODE0                  176
#define IDC_ORT_AVERAGE                 177
#define IDC_DM_B                        177
#define IDC_CO_HELP                     178
#define IDC_ORT_EMODE4                  178
#define IDC_DM_G                        179
#define IDC_AM_LIST                     180
#define IDC_DM_AON                      181
#define IDC_AM_ADD                      182
#define IDC_DM_BON                      183
#define IDC_AM_CLEAR                    184
#define IDC_DM_ZMN                      185
#define IDC_DM_APPLAY                   186
#define IDC_DM_RON                      187
#define IDC_DM_NEG                      188
#define IDC_DM_AXANGLE                  189
#define IDC_DM_CMSTEPS                  190
#define IDC_DM_DEFAULT                  191
#define IDC_ML_RAD                      192
#define IDC_DM_XSIZE                    192
#define IDC_DM_YSIZE                    193
#define IDC_DM_FIT                      194
#define IDC_INF_AZIMUTH                 195
#define IDC_INF_CS                      196
#define IDC_AM_G                        197
#define IDC_AM_AR                       198
#define IDS_PE_ABORTED                  199
#define IDC_AM_BR                       199
#define IDC_GAMMA_TXT                   200
#define IDC_ETB_RIGHT                   205
#define IDC_CO_GRAY                     206
#define IDC_CO_GDEFAULT                 207
#define IDC_CO_CUSTOM                   208
#define IDC_CO_CONTRAST                 210
#define IDC_CO_BRIGHTNESS               211
#define IDC_CO_PLOT                     212
#define IDC_CO_R                        213
#define IDC_ABOUT_VERSION               215
#define IDC_CO_EDIT                     216
#define IDC_CO_CSAVE                    217
#define IDC_CO_CLOAD                    218
#define IDC_ETB_LEFT                    219
#define IDC_PRN_TEXT1                   220
#define IDC_ETB_DELETE                  220
#define IDC_PRN_TEXT2                   221
#define IDC_ETB_AVAILABLE               221
#define IDC_PRN_TEXT0                   222
#define IDC_ETB_INSERT                  222
#define IDC_HKE_TEXT                    225
#define IDC_PS_LEFT                     225
#define IDC_HKE_LIST                    226
#define IDC_PS_RIGHT                    226
#define IDC_OR_HKEDIT                   227
#define IDC_PS_BOTTOM                   227
#define IDC_AM_CGRAV                    228
#define IDC_AM_TEXT                     229
#define IDC_HKE_UNIC                    230
#define IDC_HKE_CHAMP                   231
#define IDC_PS_TOP                      231
#define IDC_HKE_CHPHA                   232
#define IDC_HKE_CHANGE                  233
#define IDC_HKE_CHK                     234
#define IDC_PS_CENTX                    234
#define IDC_HKE_CHH                     235
#define IDC_PS_CENTY                    235
#define IDC_HKE_ADD                     236
#define IDC_PS_FOOTER                   236
#define IDC_HKE_DELETE                  237
#define IDC_PS_PRINTERNAME              237
#define IDC_HKE_APPLY                   238
#define IDC_PS_SETUP                    238
#define IDC_HKE_THRESHOLD               239
#define IDC_HKE_SAVE                    240
#define IDC_HKE_LOAD                    241
#define IDC_OR_LTITLE                   242
#define IDC_HKE_SAVE3D                  242
#define IDC_PS_PREM                     242
#define IDC_ORT_EMODE1                  243
#define IDC_ORT_EMODE2                  244
#define IDC_ORT_EMODE3                  245
#define IDC_HKE_INVERSE                 246
#define IDC_AM_SAVE                     247
#define IDC_ETB_GAP                     248
#define IDC_AM_LOAD                     249
#define IDC_I_INPUT                     250
#define IDC_INF_DEFSPREAD               250
#define IDC_ELD_PLOT                    251
#define IDC_AM_DISTITLE                 252
#define IDC_AM_DISTANCEON               253
#define IDC_AM_DISA1                    254
#define IDC_AM_DISTANCE                 255
#define IDC_AM_DISA2                    256
#define IDC_INF_DEFOCUS0                257
#define IDC_INF_CONVER                  258
#define IDC_INF_DEFOCUS1                260
#define IDC_INF_BEAMTILT                261
#define IDC_INF_VACC                    262
#define IDC_INF_SPECTILT                263
#define IDC_INF_THICKNESS               264
#define IDC_INF_DIG                     265
#define IDC_1D_PLOT                     267
#define IDC_INF_SCALE                   267
#define IDC_INF_ASPECT                  268
#define IDC_FI_C_DEFAULT                269
#define IDC_INF_MAG                     269
#define IDC_1D_COORTITLE                271
#define IDC_1D_POINT1                   272
#define IDC_1D_POINT2                   273
#define IDC_1D_DISTANCE                 274
#define IDC_1D_IFFT                     275
#define IDC_I_LIST                      275
#define IDC_ORT_ANYSHIFT                276
#define IDC_I_NAME                      276
#define IDC_1D_DISTANCE_2               276
#define IDC_FI_R_LIST                   277
#define IDC_I_CCDTYPE                   277
#define IDC_I_NEW                       278
#define IDC_ELD_K1                      279
#define IDC_I_APPLY                     279
#define IDC_FI_L_RADIUS                 280
#define IDC_I_TBC                       280
#define IDC_FI_L_CLEAR                  281
#define IDC_I_DELETE                    281
#define IDC_FI_C_AZIMUTH                282
#define IDC_I_CTRAP                     282
#define IDC_FI_C_DEFOCUS1               283
#define IDC_I_AMODE                     283
#define IDC_FI_C_DEFOCUS0               284
#define IDC_I_GPO1                      284
#define IDC_ELD_HKTEXT                  285
#define IDC_FI_L_WEIGHT                 285
#define IDC_I_GPO2                      285
#define IDC_ELD_REF1                    286
#define IDC_I_ADEPTH                    286
#define IDC_FI_C_ESTIMATE               287
#define IDC_I_DEFAULT                   287
#define IDC_1D_FFT                      288
#define IDC_1D_PROFILE                  289
#define IDC_1D_HISTO                    290
#define IDC_1D_INFO                     291
#define IDC_1D_CALCAL                   299
#define IDC_FI_PLOT                     300
#define IDC_ML_BRAD                     302
#define IDC_ML_ASS                      303
#define IDC_ML_BSS                      304
#define IDC_ELD_REF2                    305
#define IDC_ML_GSS                      306
#define IDC_FI_L_SMOOTH                 307
#define IDC_FI_L_INVERSE                308
#define IDC_FI_R_RESTORE                309
#define IDC_FI_C_AMP                    310
#define IDC_FI_C_ELLIPTIC               311
#define IDC_FI_C_SHOW                   312
#define IDC_FI_L_SHOW                   313
#define IDC_ELD_REF3                    314
#define IDC_FI_C_MATH                   314
#define IDC_ELD_AUTO                    315
#define IDC_ELD_H2                      318
#define IDC_ELD_K2                      321
#define IDC_ELD_H3                      324
#define IDC_ELD_K3                      327
#define IDC_ELD_H1                      330
#define IDC_ELD_AS                      331
#define IDC_ELD_BS                      332
#define IDC_ELD_GS                      333
#define IDC_ELD_3D_A                    334
#define IDC_ELD_UU1                     335
#define IDC_ELD_VV1                     336
#define IDC_ELD_Z2                      336
#define IDC_ELD_REFINE                  337
#define IDC_ELS_DVTO                    337
#define IDC_ELD_UU2                     338
#define IDC_ETB_COMMENT                 338
#define IDC_CO_G                        339
#define IDC_ELD_VV2                     339
#define IDC_ELD_Z4                      339
#define IDC_CO_B                        340
#define IDC_ELD_KK1                     340
#define IDC_ELS_INTO                    340
#define IDC_CO_PALLIST                  341
#define IDC_ELD_LL1                     341
#define IDC_CO_PALNAME                  342
#define IDC_ELD_HH1                     342
#define IDC_ELD_KK2                     343
#define IDC_ELD_LL2                     344
#define IDC_ELD_HH2                     345
#define IDC_FT_RESL                     345
#define IDC_ELD_NR                      346
#define IDC_ELD_AMPLITUDES              347
#define IDC_ELD_MAP                     348
#define IDC_ELD_SHAPE                   349
#define IDC_ELD_INTENSITIES             350
#define IDC_HKE_SUBFILE                 351
#define IDC_ELD_INTEGRATE_              351
#define IDC_FT_LOG                      352
#define IDC_ELD_SHAPEFIT_               352
#define IDC_ELD_LIST                    353
#define IDC_FI_C_ROOT                   354
#define IDC_ELD_3D_B                    354
#define IDC_ELD_CLRLIST                 355
#define IDC_FI_C_ROOT2                  355
#define IDC_HKE_SUBCBRD                 356
#define IDC_ELD_LZ_NUM                  356
#define IDC_ELD_PROTON                  357
#define IDC_ELD_SAVE                    358
#define IDC_ELD_ZY                      359
#define IDC_ABOUT_COPYRIGHT             360
#define IDC_ELD_CS                      360
#define IDC_HKE_SUBRESTORE              361
#define IDC_ELD_3D_C                    361
#define IDC_ELD_DRAWMARKS               362
#define IDC_ELD_DOALL                   363
#define IDC_ELD_ZX                      364
#define IDC_ELD_EXTRACT                 365
#define IDC_ABOUT_TEXT                  366
#define IDC_ELD_SYNTH                   366
#define IDC_ABOUT_NAME                  367
#define IDC_ELD_CALL_SPIN_STAR          367
#define IDC_ELD_PASS                    368
#define IDC_ELD_PASSINFO                369
#define IDC_INF_ELD                     370
#define IDC_ELD_3D_AL                   370
#define IDC_ELD_3D_BT                   371
#define IDC_CAL_STANDARD                372
#define IDC_ELD_3D_GM                   372
#define IDC_CAL_RING                    373
#define IDC_ELD_3D_A2                   373
#define IDC_CAL_RINGS                   374
#define IDC_ELD_3D_B2                   374
#define IDC_CAL_REFINE                  375
#define IDC_ELD_3D_C2                   375
#define IDC_ELD_3D_AL2                  376
#define IDC_ELD_3D_BT2                  377
#define IDC_CAL_XAVE                    378
#define IDC_ELD_3D_GM2                  378
#define IDC_ELD_PEAK_SEARCH             379
#define IDC_ELD_LIST_HEADER             380
#define IDC_CAL_YAVE                    381
#define IDC_CAL_CLEAR                   382
#define IDC_CAL_PROTOCOL                383
#define IDC_ML_CENTAB                   402
#define IDC_ML_SWAPAB                   404
#define IDC_ML_NEGA                     405
#define IDC_ML_NEGB                     406
#define IDC_ML_CENTABS                  407
#define IDC_ML_CN1S                     408
#define IDC_ML_CN1                      409
#define IDC_ML_CN2                      410
#define IDC_ML_CN3                      411
#define IDC_ML_CN2S                     412
#define IDC_ML_CN3S                     413
#define IDC_ML_AUTO                     416
#define IDC_ML_REFINE                   419
#define IDC_ML_AS                       420
#define IDC_ML_BS                       421
#define IDC_ML_GS                       422
#define IDC_ML_NEGAS                    423
#define IDC_ML_NEGBS                    424
#define IDC_ML_SWAPABS                  425
#define IDC_SD_VV1                      427
#define IDC_SD_HH1                      428
#define IDC_SD_KK1                      429
#define IDC_SD_UU2                      431
#define IDC_SD_VV2                      432
#define IDC_SD_HH2                      433
#define IDC_SD_KK2                      434
#define IDC_SD_LL2                      435
#define IDC_INF_SCALEUNITS              439
#define IDC_INF_MAGUNITS                442
#define IDC_INF_MAGFIX                  443
#define IDC_INF_DIGFIX                  444
#define IDC_INF_SCALEFIX                445
#define IDC_INF_UPDATE                  446
#define IDC_1D_XEXT                     447
#define IDC_INF_CORRECT                 447
#define IDC_1D_YEXT                     448
#define IDC_PHI_V1                      448
#define IDC_INF_SETASDEFAULT            448
#define IDC_1D_DIG                      449
#define IDC_PHI_W1                      449
#define IDC_ELD_INFO                    450
#define IDC_1D_ASPECT                   450
#define IDC_PHI_V2                      450
#define IDC_1D_WIDTH                    451
#define IDC_EDRD_PLOT                   451
#define IDC_PHI_W2                      451
#define IDC_PHI_12W                     452
#define IDC_EDRD_CENTER                 453
#define IDC_EDRD_CREFRAD                454
#define IDC_EDRD_ELL_DISTORT_TEXT       455
#define IDC_EDRD_CREFINE                456
#define IDC_EDRD_RDFCALC                457
#define IDC_EDRD_LIST                   458
#define IDC_EDRD_CLEAR                  459
#define IDC_EDRD_SAVE                   460
#define IDC_EDRD_ADDRING                461
#define IDC_EDRD_SCIRC                  462
#define IDC_EDRD_SARC                   463
#define IDC_EDRD_SUBBKG                 464
#define IDC_EDRD_RDFSAVE                465
#define IDC_EDRD_NEGAT                  466
#define IDC_EDRD_NPROF                  467
#define IDC_PHI_SAVE                    467
#define IDC_PHI_CLRLIST                 468
#define IDC_EDRD_ELL_DIST_RESET         468
#define IDC_PHI_LIST                    469
#define IDC_EDRD_CORRECT_ELL_DIST2      469
#define IDC_EDRD_CORRECT_ELL_DIST       469
#define IDC_PHI_U1                      470
#define IDC_EDRD_ELL_DIST_ESTIMATE      470
#define IDC_PHI_FIND                    471
#define IDC_EDRD_FIT_RDF                471
#define IDC_EDRD_RESET_CENTRE           472
#define IDC_PHI_LAT2                    473
#define IDC_PHI_EU1                     474
#define IDC_PHI_EV1                     475
#define IDC_PHI_EW1                     476
#define IDC_PHI_U2                      477
#define IDC_PHI_EU2                     478
#define IDC_PHI_EV2                     479
#define IDC_PHI_EW2                     480
#define IDC_PHI_12EW                    481
#define IDC_PHI_INFO                    482
#define IDC_EDRD_FWHM                   485
#define IDC_EDRD_NBINS                  486
#define IDC_ELD_USE3D                   491
#define IDC_ELD_ZONEAX                  492
#define IDC_ELD_2D3D                    493
#define IDC_ORT_HKSHIFT                 497
#define IDC_IC_SRC1                     500
#define IDC_IC_SRC2                     501
#define IDC_IC_FUNC                     502
#define IDC_IC_SRC1INFO                 503
#define IDC_IC_SRC2INFO                 504
#define IDC_IC_RESULTRANGEL             505
#define IDC_IC_MODE                     506
#define IDC_IC_816                      507
#define IDC_IC_SHFT1                    508
#define IDC_FI_L_USER                   509
#define IDC_IC_SHFT2                    509
#define IDC_FI_L_LATTICE                510
#define IDC_IC_SUBTRACT1                510
#define IDC_AX_TEXT1                    510
#define IDC_IC_RESULTRANGEH             511
#define IDC_AX_POINT1                   511
#define IDC_IC_SUBTRACT2                512
#define IDC_AX_POINT2                   512
#define IDC_AX_POINT3                   513
#define IDC_AX_POINT4                   514
#define IDC_AX_A1                       515
#define IDC_AX_A2                       516
#define IDC_AX_B1                       517
#define IDC_AX_PLOT                     518
#define IDC_AX_B2                       519
#define IDC_AX_AUPDATE                  520
#define IDC_AX_RAL                      521
#define IDC_AX_RBL                      522
#define IDC_AX_RGAMMA                   523
#define IDC_SD_UU1                      527
#define IDC_SD_LL1                      528
#define IDC_SD_ZONEAX                   529
#define IDC_ELD_NOTLISTY                531
#define IDC_ELS_DVFROM                  532
#define IDC_ELS_INFROM                  533
#define IDC_ELS_CENTONLY                534
#define IDC_EDRD_MOVECENTRE             535
#define IDC_EDRD_AUTO_CENTRE            536
#define IDC_EDRD_MANUAL_CENTRE          537
#define IDC_CO_RESTORE                  1000
#define IDC_CO_MAXIMIZEC                1002
#define IDM_F_OPEN                      1010
#define IDM_F_SAVE                      1020
#define IDC_ML_LIST_AB                  1025
#define IDC_ML_LIST_AB2                 1026
#define IDC_A_ICON                      1029
#define IDC_CO_FROM                     1034
#define IDC_I_CX0                       1034
#define IDC_CO_TO                       1035
#define IDC_FI_TABS                     1035
#define IDC_I_CY0                       1035
#define IDC_FI_LATTICE                  1036
#define IDC_I_CX1                       1036
#define IDC_FI_RADIAL                   1037
#define IDC_I_CY1                       1037
#define IDC_FI_CTF                      1038
#define IDC_I_16BIT                     1038
#define IDC_HT_LEFT                     1040
#define IDC_HT_RIGHT                    1041
#define IDC_HT_TOP                      1042
#define IDC_I_GAIN                      1043
#define IDC_I_OFFS                      1044
#define IDC_I_BRIG                      1045
#define IDC_I_CONT                      1046
#define IDC_I_GAINT                     1047
#define IDC_I_OFFST                     1048
#define IDC_I_BRIGT                     1049
#define IDM_F_GRAB                      1050
#define IDC_I_CONTT                     1050
#define IDC_I_FULLG                     1051
#define IDC_FI_L_INFO                   1052
#define IDC_FI_R_INFO                   1053
#define IDC_FI_ITEMTOPLOT               1055
#define IDC_FI_INFO                     1056
#define IDC_IC_DOIT                     1057
#define IDC_FI_BIGPLOT                  1058
#define IDM_F_PRINT                     1061
#define IDC_IE_RESTORE                  1061
#define IDC_IE_CCIRC                    1062
#define IDC_IE_FCIRC                    1063
#define IDC_IE_SQUARE                   1064
#define IDC_IE_RECT                     1065
#define IDC_IE_FREESEL                  1066
#define IDC_IE_ROTATE                   1067
#define IDC_IE_ANGLE                    1068
#define IDC_IE_CUTOUT                   1069
#define IDC_IE_CUTIN                    1070
#define IDM_F_PRINTSET                  1071
#define IDC_I_XR                        1071
#define IDC_IE_EDGE                     1071
#define IDC_I_YR                        1072
#define IDC_UB_UNBEND                   1072
#define IDC_I_EXPOSURETIME              1073
#define IDC_UB_INFO                     1074
#define IDC_UB_A                        1075
#define IDC_UB_B                        1076
#define IDC_UB_G                        1077
#define IDC_UB_AXANGLE                  1078
#define IDM_F_EXIT                      1080
#define IDC_UB_PROGRESS                 1080
#define IDC_UB_APERTURE                 1081
#define IDC_UB_ASLOPE                   1082
#define IDC_PS_NEGATIVE                 1082
#define IDC_UB_SPOTS                    1083
#define IDC_CUSTOM1                     1083
#define IDC_TSP_X0                      1084
#define IDC_TSP_Y0                      1085
#define IDC_TSP_X1                      1086
#define IDC_TSP_Y1                      1087
#define IDC_TSP_BINARY                  1088
#define IDC_ELD_YELLOW_TYPE             1089
#define IDC_ELD_BLUE_TYPE               1090
#define IDC_ML_MORE                     1090
#define IDC_ELD_VIOLET_TYPE             1091
#define IDC_ML_SMALL_AB_LATTICE         1091
#define IDC_ELD_RED_TYPE                1092
#define IDC_FI_C_ROOT1_TXT              1092
#define IDC_FI_C_ROOT2_TXT              1093
#define IDC_FI_C_AZIMUTH_TXT            1094
#define IDC_FI_C_ROOT1                  1095
#define IDC_EDRD_4CLICKS                1097
#define IDC_DEFOCUS_U                   1098
#define IDC_EDRD_ELLIPTICAL_DISTORTION  1098
#define IDC_DEFOCUS_V                   1099
#define IDM_F_FILE0                     1100
#define IDC_DEF_SPREAD                  1100
#define IDM_F_FILE1                     1101
#define IDC_THICKNESS                   1101
#define IDM_F_FILE2                     1102
#define IDC_PHIDO_ANGSTR2               1102
#define IDM_F_FILE3                     1103
#define IDC_PHIDO_ANGSTR1               1103
#define IDM_F_FILE4                     1104
#define IDM_F_FILE5                     1105
#define IDM_F_FILE6                     1106
#define IDC_GRABBERS_LIST               1106
#define IDM_F_FILE7                     1107
#define IDC_EXPOSURE                    1107
#define IDC_MV_40_EXPOSURE_SLIDER       1107
#define IDM_F_FILE8                     1108
#define IDC_MV_40_EXPOSURE_EDIT         1108
#define IDM_F_FILE9                     1109
#define IDC_RAW_FILE_WIDTH              1109
#define IDC_RAW_FILE_HEIGHT             1110
#define IDC_RAW_FILE_8_BIT              1111
#define IDC_RAW_FILE_16_BIT             1112
#define IDC_ELD_DEFINE_HOLZ             1112
#define IDC_RAW_FILE_HEADER             1113
#define IDC_ELD_LAUE_ZONES              1113
#define IDC_ELD_SHOW_LAUE_CIRCLES       1114
#define IDC_ELD_REFLECTION_MODE         1115
#define IDC_ELD_SHOW_HOLZ_AXES          1115
#define IDC_ELD_DEFINE_LAUE_CIRCLE      1116
#define IDC_ELD_LAUE_ZONE_NR            1117
#define IDC_EDRD_LOCATE_OPPOSITE        1118
#define IDC_3D_CELL_TITLE               1119
#define IDC_3D_CELL_TYPE                1120
#define IDC_ELD_INTENSITY_TYPE          1121
#define IDC_FT_RESL_TEXT                1127
#define IDC_ORT_SYNAME1_TEXT            1134
#define ID_ORIGIN_REFINEMENT            1135
#define IDC_ORIGIN_REFINEMENT           1135
#define IDM_E_COPY                      1210
#define IDM_E_XCOPY                     1220
#define IDM_E_PASTE                     1230
#define IDM_E_ICALC                     1240
#define IDM_V_TOOL                      1410
#define IDM_V_EDITTOOL                  1420
#define IDM_V_STATUS                    1430
#define IDM_V_COLORS                    1440
#define IDM_V_NAVIG                     1450
#define IDM_V_FIT                       1460
#define IDM_V_SETINPUT                  1470
#define IDM_V_INFO                      1480
#define IDM_A_AR128                     1510
#define IDM_A_AR256                     1520
#define IDM_A_AR512                     1530
#define IDM_A_AR1K                      1540
#define IDM_A_ARFREE                    1550
#define IDM_A_DIGI                      1560
#define IDM_A_FILT                      1710
#define IDM_A_IFFT                      1720
#define IDM_C_LREF                      1810
#define IDM_C_OREF                      1820
#define IDM_C_DMAP                      1830
#define IDM_C_AMTR                      1840
#define IDM_C_ONED                      1850
#define IDM_C_AXTAL                     1860
#define IDM_E_ELD                       1910
#define IDM_E_CAL                       1920
#define IDM_E_PHIDO                     1930
#define IDM_E_EDRD                      1940
#define IDM_L_OPTIONS                   2010
#define IDM_L_EDITTOP                   2020
#define IDM_L_CHGRABBER                 2030
#define IDM_W_CASCADE                   2110
#define IDM_W_HTILE                     2120
#define IDM_W_VTILE                     2130
#define IDM_W_IARRANGE                  2140
#define IDM_W_CLOSEALL                  2150
#define IDM_W_NEXT                      2160
#define IDM_W_CLOSE                     2170
#define IDM_H_CONTENTS                  2510
#define IDM_H_HELPONHELP                2520
#define IDM_H_ABOUT                     2530
#define IDM_W_CHILDS                    8000
#define IDM_S_CCIRC                     9000
#define IDM_S_FCIRC                     9050
#define IDM_S_SQUARE                    9100
#define IDM_S_RECT                      9150
#define IDM_S_FREESEL                   9200
#define IDM_S_CUTIN                     9250
#define IDM_S_CUTOUT                    9300
#define IDM_S_CUTUNDO                   9350
#define IDM_S_EDGE                      9400
#define IDM_S_ROTATE                    9450
#define IDM_F_IMAGE                     9999
#define IDC_CANCEL                      9999
#define SC_myZOOM                       0x4000
#define SC_Z11                          0x4110
#define SC_Z12                          0x4120
#define SC_Z13                          0x4130
#define SC_Z14                          0x4140
#define SC_Z15                          0x4150
#define SC_Z16                          0x4160
#define SC_Z17                          0x4170
#define SC_Z18                          0x4180
#define SC_Z21                          0x4210
#define SC_Z31                          0x4310
#define SC_Z41                          0x4410
#define SC_Z81                          0x4810
#define IDC_INF_MAGBOX                  32000
#define IDC_INF_SCALEBOX                32001
#define IDS_MORECOLORS                  0x800C
#define ID_BUTTONA                      40001
#define ID_BUTTON40004                  40004
#define ID_BUTTON40005                  40005
#define ID_BUTTON40006                  40006
#define ID_BUTTON40007                  40007
#define ID_BUTTON40008                  40008
#define ID_BUTTON40011                  40011
#define ID_BUTTON40012                  40012
#define ID_BUTTON40013                  40013
#define ID_BUTTON40014                  40014
#define ID_BUTTON40015                  40015
#define ID_BUTTON40016                  40016
#define ID_BUTTON40017                  40017
#define IDM_C_HIST                      40018
#define IDM_C_CORR                      40019
#define IDM_C_FFT                       40020
#define IDM_RI_10                       40021
#define IDM_RI_9                        40022
#define IDM_RI_8                        40023
#define IDM_RI_7                        40024
#define IDM_RI_6                        40025
#define IDM_RI_5                        40026
#define IDM_RI_4                        40027
#define IDM_RI_3                        40028
#define IDM_RI_2                        40029
#define IDM_RI_1                        40030
#define IDM_RI_0                        40031
#define IDM_RI_M1                       40032
#define IDM_RI_M2                       40033
#define IDM_RI_M3                       40034
#define IDM_RI_M4                       40035
#define IDM_RI_M5                       40036
#define IDM_RI_M6                       40037
#define IDM_RI_M7                       40038
#define IDM_RI_M8                       40039
#define IDM_RI_M9                       40040
#define IDM_RI_M10                      40041
#define IDM_RI_SPIN                     40042
#define ID_BUTTON40043                  40043
#define ID_BUTTON40047                  40047
#define IDHM_LEFT                       40048
#define IDHM_RIGHT                      40049
#define IDHM_ZOOMX                      40050
#define IDHM_TOP                        40051
#define IDHM_ZOOMY                      40052
#define IDHM_FULL                       40053
#define IDHM_SMOOTH                     40054
#define IDM_OM_PAL1                     40056
#define IDM_OM_PAL2                     40057
#define IDM_OM_PAL3                     40058
#define IDM_OM_PAL4                     40059
#define IDM_OM_PALGRAY                  40060
#define IDM_OM_TUNE                     40061
#define ID_MENUITEM40062                40062
#define IDM_V_SELECTET                  40062
#define ID_BUTTON40063                  40063
#define ID_BUTTON40064                  40064
#define ID_BUTTON40065                  40065
#define ID_BUTTON40066                  40066
#define ID_BUTTON40067                  40067
#define ID_BUTTON40068                  40068
#define ID_BUTTON40069                  40069
#define ID_BUTTON40070                  40070
#define ID_BUTTON40071                  40071
#define ID_BUTTON40072                  40072
#define IDHM_TUNE                       40073
#define ID_BUTTON40075                  40075
#define ID_BUTTON40076                  40076
#define ID_BUTTON40077                  40077
#define ID_BUTTON40078                  40078
#define ID_BUTTON40079                  40079
#define ID_BUTTON40080                  40080
#define ID_BUTTON40081                  40081
#define ID_BUTTON40082                  40082
#define IDM_V_ICALC                     40083
#define IDM_C_UBEND                     40085
#define IDM_A_AR2K                      40086
#define IDM_A_AR4K                      40087
#define IDM_F_SSAVE                     40088
#define IDM_OM_INVERT                   40089
#define ID_BUTTON40090                  40090
#define ID_BUTTON40092                  40092
#define ID_BUTTON40093                  40093
#define ID_BUTTON40094                  40094
#define ID_BUTTON40095                  40095
#define ID_BUTTON40096                  40096
#define ID_BUTTON40097                  40097
#define ID_BUTTON40098                  40098
#define ID_BUTTON40099                  40099
#define IDM_F_BWCORR                    40100
#define IDC_B_ANGSTR                    40101
#define ID_BUTTON40101                  40101
#define IDC_PHIDO_ANGSTR3               40102
#define IDM_F_TVIPS_ACQUIRE_IMG         40102
#define IDC_PHIDO_ANGSTR4               40103
#define IDM_F_TVIPS_GET_IMG             40103
#define IDC_PHIDO_ANGSTR5               40104
#define IDM_F_TVIPS_GET_EM_VEC          40104
#define IDC_PHIDO_ANGSTR6               40105
#define IDM_F_OPEN_ELD                  40105
#define IDC_PHIDO_ANGSTR7               40106
#define IDC_AMTR_A_ANGSTR               40107
#define IDC_AMTR_B_ANGSTR               40108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         40106
#define _APS_NEXT_CONTROL_VALUE         1136
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
